# Sistema de Recomendacion

Buscar perfiles de departamentos dentro de un mismo "Cluster" usando Sistema de Recomendacion

In [1]:
# Librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv('Data_clust_oficial.csv')

In [3]:
data.head(3)

,Unnamed: 0,YEAR,UBIGEO,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,...,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA,cluster_std,latitud,longitud
0,0,2018,10202,7,7,0,0,0,24,0,...,0.0,13.0,3.0,3.0,0.0,0.0,2.0,1,-5.4164,-78.4378
1,1,2018,10201,7,4,13,9,6,45,12,...,0.0,7.0,0.0,2.0,0.0,0.0,2.0,1,-5.6389,-78.5311
2,2,2018,10203,7,6,2,3,0,21,2,...,0.0,4.0,1.0,1.0,0.0,0.0,2.0,1,-5.6750,-78.4231

In [4]:
data.shape

(13344, 72)

In [5]:
data.isnull().sum()

Unnamed: 0             0
YEAR                   0
UBIGEO                 0
DOMINIO                0
ESTRATO                0
                      ..
Proyectos_inversion    0
ZONA                   1
cluster_std            0
latitud                1
longitud               1
Length: 72, dtype: int64

## Consideraciones

Se acuerdo a las caracteristicas de los cluster. El cluster 2 tiene el perfil de que sus Viviendas vulnerables (-seguro, +sismos). Adicionakmente, solo se acotara el espectro del analisis para el ultimo año disponible de los datos. Finalmente, de los registros del cluster, se seleccionara el perfil del distrito con mas propension a no estar preparado en caso de un movimiento sismico.

In [8]:
data_seleccionada = data[(data['YEAR'] == 2022) & (data['cluster_std'] == 1)].copy()

In [9]:
data_seleccionada.shape

(478, 72)

In [10]:
num_filas, num_columnas = data_seleccionada.shape
print(f"La cantidad de filas es: {num_filas}")
print(f"La cantidad de columnas es: {num_columnas}")

La cantidad de filas es: 478
La cantidad de columnas es: 72

In [12]:
data_seleccionada.columns

Index(['Unnamed: 0', 'YEAR', 'UBIGEO', 'DOMINIO', 'ESTRATO',
       'Registro_SUNARP_SI', 'Registro_SUNARP_NO', 'Asistencia_Tecnica_SI',
       'Asistencia_Tecnica_NO', 'Asistencia_Tecnica_NOSABE', 'Licencia_SI',
       'Licencia_NO', 'Licencia_NOSABE', 'Tipo_casa_Independiente',
       'Tipo_casa_Departamento', 'Tipo_casa_Quinta', 'Tipo_casa_Vecindad',
       'Tipo_casa_Choza', 'Tipo_casa_Improvisada', 'Tipo_casa_No_habitable',
       'Tipo_casa_Otro', 'Pared_Ladrillo', 'Pared_Piedra_sillar',
       'Pared_Adobe', 'Pared_Tapia', 'Pared_Quincha', 'Pared_Piedra_barro',
       'Pared_Madera', 'Pared_Tripley', 'Piso_MaderaPulida',
       'Piso_LaminasAsfalticas', 'Piso_Losetas', 'Piso_Madera', 'Piso_Cemento',
       'Piso_Tierra', 'Piso_Otro', 'Techo_Concreto', 'Techo_Madera',
       'Techo_Tejas', 'Techo_Calamina', 'Techo_Caña', 'Techo_Triplay',
       'Techo_Paja', 'Techo_Otro', 'Nivel_Casa_Alquilada',
       'Nivel_Casa_PropiaPagada', 'Nivel_Casa_PropiaInvasion',
       'Nivel_Casa_PropiaCredito', 'Nivel_Casa_CedidaTrabajo',
       'Nivel_Casa_CedidaInstitución', 'Nivel_Casa_Otro',
       'Titulo_propiedad_SI', 'Titulo_propiedad_NO',
       'Titulo_propiedad_Tramite', 'Conteo_viviendas', 'region', 'provincia',
       'distrito', 'Key', 'Conteo_sismos', 'Promedio', 'Min_Mag', 'Max_Mag',
       'Categoria_I-1', 'Categoria_I-2', 'Categoria_I-3', 'Categoria_I-4',
       'Proyectos_inversion', 'ZONA', 'cluster_std', 'latitud', 'longitud'],
      dtype='object')

In [16]:
data_seleccionada.Conteo_sismos.unique()  #.max()

array([0., 1., 2., 7., 6., 3.])

In [ ]:
data_seleccionada.Asistencia_Tecnica_NO.unique().max()

In [18]:
registro = data_seleccionada[(data_seleccionada['Asistencia_Tecnica_NO']<=data_seleccionada.Asistencia_Tecnica_NO.unique().max()) & 
                             (data_seleccionada['Conteo_sismos']==data_seleccionada.Conteo_sismos.unique().max())]
registro

,Unnamed: 0,YEAR,UBIGEO,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,...,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA,cluster_std,latitud,longitud
8996,8996,2022,40301,3,5,10,1,8,3,0,...,5.6,0.0,0.0,1.0,0.0,0.0,4.0,1,-15.7725,-73.3658

In [19]:
registro.Asistencia_Tecnica_NO

8996    3
Name: Asistencia_Tecnica_NO, dtype: int64

In [17]:
registro.Conteo_sismos

9178    0.0
Name: Conteo_sismos, dtype: float64

In [22]:
for columna, valor in registro.iloc[0].items():
    print(f"{columna}: {valor}")

Unnamed: 0: 8996
YEAR: 2022
UBIGEO: 40301
DOMINIO: 3
ESTRATO: 5
Registro_SUNARP_SI: 10
Registro_SUNARP_NO: 1
Asistencia_Tecnica_SI: 8
Asistencia_Tecnica_NO: 3
Asistencia_Tecnica_NOSABE: 0
Licencia_SI: 8
Licencia_NO: 3
Licencia_NOSABE: 0
Tipo_casa_Independiente: 9
Tipo_casa_Departamento: 0
Tipo_casa_Quinta: 0
Tipo_casa_Vecindad: 2
Tipo_casa_Choza: 0
Tipo_casa_Improvisada: 0
Tipo_casa_No_habitable: 0.0
Tipo_casa_Otro: 0.0
Pared_Ladrillo: 7
Pared_Piedra_sillar: 0
Pared_Adobe: 3
Pared_Tapia: 0
Pared_Quincha: 0
Pared_Piedra_barro: 0
Pared_Madera: 1
Pared_Tripley: 0
Piso_MaderaPulida: 0
Piso_LaminasAsfalticas: 0
Piso_Losetas: 1
Piso_Madera: 0
Piso_Cemento: 9
Piso_Tierra: 1
Piso_Otro: 0
Techo_Concreto: 7
Techo_Madera: 0
Techo_Tejas: 0
Techo_Calamina: 4
Techo_Caña: 0
Techo_Triplay: 0
Techo_Paja: 0
Techo_Otro: 0
Nivel_Casa_Alquilada: 0
Nivel_Casa_PropiaPagada: 10
Nivel_Casa_PropiaInvasion: 0
Nivel_Casa_PropiaCredito: 1
Nivel_Casa_CedidaTrabajo: 0
Nivel_Casa_CedidaInstitución: 0
Nivel_Casa_Otro: 0
Titulo_propiedad_SI: 11
Titulo_propiedad_NO: 0
Titulo_propiedad_Tramite: 0
Conteo_viviendas: 19
region: AREQUIPA
provincia: CARAVELI
distrito: CARAVELI
Key: AREQUIPACARAVELICARAVELI2022
Conteo_sismos: 7.0
Promedio: 4.442857142857143
Min_Mag: 4.0
Max_Mag: 5.6
Categoria_I-1: 0.0
Categoria_I-2: 0.0
Categoria_I-3: 1.0
Categoria_I-4: 0.0
Proyectos_inversion: 0.0
ZONA: 4.0
cluster_std: 1
latitud: -15.7725
longitud: -73.3658

El registro seleccionado tiene la caracteristica de 8 viviendas que presentan Asistencia Tecnica y otras 3 que no. 4 Presentan techo con calamina pero 7 con paredes de ladrillo. El Registro se encuentra en Arequipa, Provincia de Careveli. Adicionalmente, es el registro con el maximo numero de sismos contados en el año 2022. Y no hay presencia de ningun poryecto de Invesion

# Parte Sistema de Recomendacion con Filtrado Colaborativo

In [23]:
#Subset de registros Distritos
data_seleccionada.shape

(478, 72)

In [25]:
#Districo seleccionado como perfil
registro.shape

(1, 72)

In [26]:
# Quitamos en ambos las caolumnas no numericas, ya que ára hacer la comparacion entre mi usuario consulta 
#(distrito y el sub sed, los datos ddeben estan en valor numerico)
data_seleccionada = data_seleccionada.select_dtypes(exclude=['object'])
data_seleccionada.fillna(0, inplace=True)

registro = registro.select_dtypes(exclude=['object'])
registro.fillna(0, inplace=True)

In [28]:
data_seleccionada.shape

(478, 68)

In [29]:
registro.shape

(1, 68)

In [30]:
registro.head(1)

,Unnamed: 0,YEAR,UBIGEO,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,...,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA,cluster_std,latitud,longitud
8996,8996,2022,40301,3,5,10,1,8,3,0,...,5.6,0.0,0.0,1.0,0.0,0.0,4.0,1,-15.7725,-73.3658

In [34]:
df_distritos = data_seleccionada.drop(['Unnamed: 0', 'YEAR','UBIGEO','latitud','longitud','cluster_std'], axis=1)
df_distritos

,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,Licencia_SI,Licencia_NO,Licencia_NOSABE,...,Conteo_sismos,Promedio,Min_Mag,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA
8775,7,7,4,4,0,52,0,0,52,0,...,0.0,0.0,0.0,0.0,13.0,3.0,3.0,0.0,1.0,2.0
8776,7,5,13,1,5,55,12,11,50,11,...,0.0,0.0,0.0,0.0,7.0,0.0,2.0,0.0,0.0,2.0
8777,7,5,3,1,1,10,0,2,9,0,...,0.0,0.0,0.0,0.0,4.0,1.0,1.0,0.0,0.0,2.0
8778,7,7,0,3,1,70,1,1,70,1,...,1.0,5.0,5.0,5.0,29.0,5.0,5.0,0.0,0.0,2.0
8779,7,6,5,1,0,18,1,1,17,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9248,6,5,7,0,3,8,0,2,9,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0
9249,6,7,0,0,0,8,0,0,8,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
9250,6,6,4,0,0,7,0,0,7,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0
9251,6,6,0,1,1,12,1,1,12,1,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,2.0
9252,6,6,3,1,5,14,0,5,14,0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,2.0

In [33]:
df_un_distrito = registro.drop(['Unnamed: 0', 'YEAR','UBIGEO','latitud','longitud','cluster_std'], axis=1)
df_un_distrito

,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,Licencia_SI,Licencia_NO,Licencia_NOSABE,...,Conteo_sismos,Promedio,Min_Mag,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA
8996,3,5,10,1,8,3,0,8,3,0,...,7.0,4.442857,4.0,5.6,0.0,0.0,1.0,0.0,0.0,4.0

## Similaridad de Coseno

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
# Calcular la similitud del coseno entre el distrito seleccionado y cada registro en el subconjunto
cosine_similarities = cosine_similarity(df_un_distrito, df_distritos)

# Crear un DataFrame con los resultados y asignar el resultado a una columna en df_distritos
df_distritos['Similitud_coseno'] = cosine_similarities.flatten()

In [60]:
df_distritos.head(2)

,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,Licencia_SI,Licencia_NO,Licencia_NOSABE,...,Min_Mag,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA,Similitud_coseno,Correlacion_Pearson
8775,7,7,4,4,0,52,0,0,52,0,...,0.0,0.0,13.0,3.0,3.0,0.0,1.0,2.0,0.618735,0.496507
8776,7,5,13,1,5,55,12,11,50,11,...,0.0,0.0,7.0,0.0,2.0,0.0,0.0,2.0,0.727597,0.627960

In [38]:
df_distritos_sorted = df_distritos.sort_values(by='Similitud_coseno', ascending=False)

In [44]:
df_distritos_sorted.columns

Index(['DOMINIO', 'ESTRATO', 'Registro_SUNARP_SI', 'Registro_SUNARP_NO',
       'Asistencia_Tecnica_SI', 'Asistencia_Tecnica_NO',
       'Asistencia_Tecnica_NOSABE', 'Licencia_SI', 'Licencia_NO',
       'Licencia_NOSABE', 'Tipo_casa_Independiente', 'Tipo_casa_Departamento',
       'Tipo_casa_Quinta', 'Tipo_casa_Vecindad', 'Tipo_casa_Choza',
       'Tipo_casa_Improvisada', 'Tipo_casa_No_habitable', 'Tipo_casa_Otro',
       'Pared_Ladrillo', 'Pared_Piedra_sillar', 'Pared_Adobe', 'Pared_Tapia',
       'Pared_Quincha', 'Pared_Piedra_barro', 'Pared_Madera', 'Pared_Tripley',
       'Piso_MaderaPulida', 'Piso_LaminasAsfalticas', 'Piso_Losetas',
       'Piso_Madera', 'Piso_Cemento', 'Piso_Tierra', 'Piso_Otro',
       'Techo_Concreto', 'Techo_Madera', 'Techo_Tejas', 'Techo_Calamina',
       'Techo_Caña', 'Techo_Triplay', 'Techo_Paja', 'Techo_Otro',
       'Nivel_Casa_Alquilada', 'Nivel_Casa_PropiaPagada',
       'Nivel_Casa_PropiaInvasion', 'Nivel_Casa_PropiaCredito',
       'Nivel_Casa_CedidaTrabajo', 'Nivel_Casa_CedidaInstitución',
       'Nivel_Casa_Otro', 'Titulo_propiedad_SI', 'Titulo_propiedad_NO',
       'Titulo_propiedad_Tramite', 'Conteo_viviendas', 'Conteo_sismos',
       'Promedio', 'Min_Mag', 'Max_Mag', 'Categoria_I-1', 'Categoria_I-2',
       'Categoria_I-3', 'Categoria_I-4', 'Proyectos_inversion', 'ZONA',
       'Similitud_coseno'],
      dtype='object')

In [40]:
df_distritos_sorted.head(4)

,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,Licencia_SI,Licencia_NO,Licencia_NOSABE,...,Promedio,Min_Mag,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA,Similitud_coseno
8996,3,5,10,1,8,3,0,8,3,0,...,4.442857,4.0,5.6,0.0,0.0,1.0,0.0,0.0,4.0,1.000000
9019,3,4,14,0,4,10,2,6,8,2,...,4.000000,3.9,4.1,0.0,1.0,0.0,1.0,0.0,4.0,0.930962
8986,3,4,7,0,4,7,0,6,5,0,...,4.700000,4.7,4.7,0.0,0.0,1.0,0.0,4.0,4.0,0.919634
8984,6,6,6,1,3,5,0,3,5,0,...,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,0.893272

## Similaridad de Person

In [58]:
# Excluir la columna 'Similitud_coseno' de las columnas numéricas
columnas_numericas = df_distritos.select_dtypes(include=['float64', 'int64']).columns
columnas_numericas = columnas_numericas.difference(['Similitud_coseno'])

# Calcula la correlación de Pearson para el registro seleccionado con respecto a df_distritos
correlaciones = df_distritos[columnas_numericas].apply(lambda row: row.corr(df_un_distrito.iloc[0][columnas_numericas]), axis=1)

# Agrega la columna de correlaciones al DataFrame del subset
df_distritos['Correlacion_Pearson'] = correlaciones

# Ordena el DataFrame de subset de mayor a menor basado en la correlación de Pearson
df_distritos_corre = df_distritos.sort_values(by='Correlacion_Pearson', ascending=False).copy()

In [59]:
df_distritos_corre.head(4)

,DOMINIO,ESTRATO,Registro_SUNARP_SI,Registro_SUNARP_NO,Asistencia_Tecnica_SI,Asistencia_Tecnica_NO,Asistencia_Tecnica_NOSABE,Licencia_SI,Licencia_NO,Licencia_NOSABE,...,Min_Mag,Max_Mag,Categoria_I-1,Categoria_I-2,Categoria_I-3,Categoria_I-4,Proyectos_inversion,ZONA,Similitud_coseno,Correlacion_Pearson
8996,3,5,10,1,8,3,0,8,3,0,...,4.0,5.6,0.0,0.0,1.0,0.0,0.0,4.0,1.000000,1.000000
9019,3,4,14,0,4,10,2,6,8,2,...,3.9,4.1,0.0,1.0,0.0,1.0,0.0,4.0,0.930962,0.903328
8986,3,4,7,0,4,7,0,6,5,0,...,4.7,4.7,0.0,0.0,1.0,0.0,4.0,4.0,0.919634,0.884957
8984,6,6,6,1,3,5,0,3,5,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,0.893272,0.854085

In [61]:
## Ver cada registro 
# Filtrar el registro con el índice 1 usando iloc
registro_1 = data.iloc[9019]
registro_2 = data.iloc[8986]
registro_3 = data.iloc[8984]

In [64]:
# el primer mas similar
for columna, valor in data.iloc[9019].items():
    print(f"{columna}: {valor}")

Unnamed: 0: 9019
YEAR: 2022
UBIGEO: 40701
DOMINIO: 3
ESTRATO: 4
Registro_SUNARP_SI: 14
Registro_SUNARP_NO: 0
Asistencia_Tecnica_SI: 4
Asistencia_Tecnica_NO: 10
Asistencia_Tecnica_NOSABE: 2
Licencia_SI: 6
Licencia_NO: 8
Licencia_NOSABE: 2
Tipo_casa_Independiente: 16
Tipo_casa_Departamento: 0
Tipo_casa_Quinta: 0
Tipo_casa_Vecindad: 0
Tipo_casa_Choza: 0
Tipo_casa_Improvisada: 0
Tipo_casa_No_habitable: 0.0
Tipo_casa_Otro: 0.0
Pared_Ladrillo: 13
Pared_Piedra_sillar: 0
Pared_Adobe: 0
Pared_Tapia: 0
Pared_Quincha: 0
Pared_Piedra_barro: 0
Pared_Madera: 2
Pared_Tripley: 0
Piso_MaderaPulida: 0
Piso_LaminasAsfalticas: 1
Piso_Losetas: 3
Piso_Madera: 1
Piso_Cemento: 11
Piso_Tierra: 0
Piso_Otro: 0
Techo_Concreto: 10
Techo_Madera: 0
Techo_Tejas: 0
Techo_Calamina: 6
Techo_Caña: 0
Techo_Triplay: 0
Techo_Paja: 0
Techo_Otro: 0
Nivel_Casa_Alquilada: 1
Nivel_Casa_PropiaPagada: 14
Nivel_Casa_PropiaInvasion: 0
Nivel_Casa_PropiaCredito: 0
Nivel_Casa_CedidaTrabajo: 0
Nivel_Casa_CedidaInstitución: 1
Nivel_Casa_Otro: 0
Titulo_propiedad_SI: 14
Titulo_propiedad_NO: 0
Titulo_propiedad_Tramite: 0
Conteo_viviendas: 19
region: AREQUIPA
provincia: ISLAY
distrito: MOLLENDO
Key: AREQUIPAISLAYMOLLENDO2022
Conteo_sismos: 3.0
Promedio: 4.0
Min_Mag: 3.9
Max_Mag: 4.1
Categoria_I-1: 0.0
Categoria_I-2: 1.0
Categoria_I-3: 0.0
Categoria_I-4: 1.0
Proyectos_inversion: 0.0
ZONA: 4.0
cluster_std: 1
latitud: -17.0292
longitud: -72.0164

In [65]:
# el Segundo mas similar
for columna, valor in data.iloc[8986].items():
    print(f"{columna}: {valor}")

Unnamed: 0: 8986
YEAR: 2022
UBIGEO: 40201
DOMINIO: 3
ESTRATO: 4
Registro_SUNARP_SI: 7
Registro_SUNARP_NO: 0
Asistencia_Tecnica_SI: 4
Asistencia_Tecnica_NO: 7
Asistencia_Tecnica_NOSABE: 0
Licencia_SI: 6
Licencia_NO: 5
Licencia_NOSABE: 0
Tipo_casa_Independiente: 9
Tipo_casa_Departamento: 0
Tipo_casa_Quinta: 0
Tipo_casa_Vecindad: 2
Tipo_casa_Choza: 0
Tipo_casa_Improvisada: 0
Tipo_casa_No_habitable: 0.0
Tipo_casa_Otro: 0.0
Pared_Ladrillo: 10
Pared_Piedra_sillar: 0
Pared_Adobe: 1
Pared_Tapia: 0
Pared_Quincha: 0
Pared_Piedra_barro: 0
Pared_Madera: 0
Pared_Tripley: 0
Piso_MaderaPulida: 0
Piso_LaminasAsfalticas: 3
Piso_Losetas: 0
Piso_Madera: 0
Piso_Cemento: 8
Piso_Tierra: 0
Piso_Otro: 0
Techo_Concreto: 8
Techo_Madera: 0
Techo_Tejas: 0
Techo_Calamina: 2
Techo_Caña: 1
Techo_Triplay: 0
Techo_Paja: 0
Techo_Otro: 0
Nivel_Casa_Alquilada: 0
Nivel_Casa_PropiaPagada: 7
Nivel_Casa_PropiaInvasion: 0
Nivel_Casa_PropiaCredito: 1
Nivel_Casa_CedidaTrabajo: 0
Nivel_Casa_CedidaInstitución: 3
Nivel_Casa_Otro: 0
Titulo_propiedad_SI: 7
Titulo_propiedad_NO: 0
Titulo_propiedad_Tramite: 1
Conteo_viviendas: 13
region: AREQUIPA
provincia: CAMANA
distrito: CAMANA
Key: AREQUIPACAMANACAMANA2022
Conteo_sismos: 1.0
Promedio: 4.7
Min_Mag: 4.7
Max_Mag: 4.7
Categoria_I-1: 0.0
Categoria_I-2: 0.0
Categoria_I-3: 1.0
Categoria_I-4: 0.0
Proyectos_inversion: 4.0
ZONA: 4.0
cluster_std: 1
latitud: -16.6247
longitud: -72.7114

In [66]:
# el Segundo mas similar
for columna, valor in data.iloc[8984].items():
    print(f"{columna}: {valor}")

Unnamed: 0: 8984
YEAR: 2022
UBIGEO: 40127
DOMINIO: 6
ESTRATO: 6
Registro_SUNARP_SI: 6
Registro_SUNARP_NO: 1
Asistencia_Tecnica_SI: 3
Asistencia_Tecnica_NO: 5
Asistencia_Tecnica_NOSABE: 0
Licencia_SI: 3
Licencia_NO: 5
Licencia_NOSABE: 0
Tipo_casa_Independiente: 7
Tipo_casa_Departamento: 0
Tipo_casa_Quinta: 0
Tipo_casa_Vecindad: 1
Tipo_casa_Choza: 0
Tipo_casa_Improvisada: 0
Tipo_casa_No_habitable: 0.0
Tipo_casa_Otro: 0.0
Pared_Ladrillo: 6
Pared_Piedra_sillar: 2
Pared_Adobe: 0
Pared_Tapia: 0
Pared_Quincha: 0
Pared_Piedra_barro: 0
Pared_Madera: 0
Pared_Tripley: 0
Piso_MaderaPulida: 0
Piso_LaminasAsfalticas: 0
Piso_Losetas: 3
Piso_Madera: 0
Piso_Cemento: 5
Piso_Tierra: 0
Piso_Otro: 0
Techo_Concreto: 6
Techo_Madera: 0
Techo_Tejas: 0
Techo_Calamina: 2
Techo_Caña: 0
Techo_Triplay: 0
Techo_Paja: 0
Techo_Otro: 0
Nivel_Casa_Alquilada: 0
Nivel_Casa_PropiaPagada: 8
Nivel_Casa_PropiaInvasion: 0
Nivel_Casa_PropiaCredito: 0
Nivel_Casa_CedidaTrabajo: 0
Nivel_Casa_CedidaInstitución: 0
Nivel_Casa_Otro: 0
Titulo_propiedad_SI: 7
Titulo_propiedad_NO: 0
Titulo_propiedad_Tramite: 1
Conteo_viviendas: 13
region: AREQUIPA
provincia: AREQUIPA
distrito: YARABAMBA
Key: AREQUIPAAREQUIPAYARABAMBA2022
Conteo_sismos: 0.0
Promedio: 0.0
Min_Mag: 0.0
Max_Mag: 0.0
Categoria_I-1: 0.0
Categoria_I-2: 1.0
Categoria_I-3: 0.0
Categoria_I-4: 0.0
Proyectos_inversion: 0.0
ZONA: 4.0
cluster_std: 1
latitud: -16.5467
longitud: -71.4756